import { dir } from 'i18next';
import { Inter } from 'next/font/google';

import type { Metadata } from 'next';
import type { ILayout } from './interfaces/IPage';

import './sass/globals.scss';

import { languages } from '@/i18n/settings';
import StoreProvider from '@/providers/StoreProvider/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: {
    lng,
  },
}: ILayout) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
